1 3 1
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.


In [7]:
import numpy as np

arr = np.zeros((8,8), int )
arr [1::2,::2] = 1
arr [::2,1::2] = 1
print(arr)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1 3 2 
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [10]:
import numpy as np

arr = np.zeros((5,5),int)
arr += np.arange(0,5)
print (arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3
Создать массив 3x3x3 со случайными значениями.

In [15]:
import numpy as np

np.random.randint (0, 100, (3, 3,3))

array([[[34, 80, 53],
        [47, 66, 13],
        [20, 44, 69]],

       [[80, 80, 45],
        [85, 52, 84],
        [64, 33, 88]],

       [[24, 65, 51],
        [88, 90, 65],
        [33, 59, 24]]])