1 3 1
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.


In [60]:
import numpy as np

arr = np.zeros((8,8), int )
arr [1::2,::2] = 1
arr [::2,1::2] = 1
print(arr)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1 3 2 
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [10]:
import numpy as np

arr = np.zeros((5,5),int)
arr += np.arange(0,5)
print (arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3
Создать массив 3x3x3 со случайными значениями.

In [59]:
import numpy as np

np.random.randint (0, 100, (3, 3,3))

array([[[62, 62, 60],
        [70, 22, 82],
        [27, 61, 52]],

       [[79, 81, 92],
        [41, 75, 71],
        [22, 37,  1]],

       [[67, 21, 41],
        [43, 22, 23],
        [39, 24, 67]]])

1.3.4 Создать матрицу с 0 внутри, и 1 на границах.

In [58]:
import numpy as np

arr = np.ones((5,5),int)
arr[1:-1,1:-1] = 0
print (arr)





[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


1.3.5 Создайте массив и отсортируйте его по убыванию.

In [57]:
import numpy as np 

np.sort(np.random.randint(0,100,10))

array([16, 18, 42, 63, 78, 79, 83, 85, 90, 97])

1.3.6 Создайте матрицу, выведите ее форму, размер и размерность.

In [55]:
import numpy as np 
y = np.random.randint(0,100,(3,3))
print (y.shape) #size




(3, 3)


2.3.1 Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [54]:
import pandas as pd
import numpy as np

a = pd.Series(np.random.randint(0,10,(5)))
b = pd.Series(np.random.randint(0,10,(5)))

c = sum((a - b)**2)**0.5
print (c)

10.099504938362077


2.3.2 
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [53]:
import pandas as pd
import numpy as np

url = "https://github.com/akmand/datasets/blob/main/baseball.csv"
dataframe = pd.read_csv(url) 


ParserError: Error tokenizing data. C error: Expected 1 fields in line 27, saw 367
