1.2.1 
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [11]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]) 
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.2.2
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [12]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20) 
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


1.2.3
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [13]:
Z = np.random.random((10,10)) 
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean() 
print(Zmin, Zmax, Zmean)

0.012867515463306556 0.9903515174197042 0.502843420634133


1.2.4 
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами

In [14]:
A = np.arange(25).reshape(5,5) 
A[[0,1]] = A[[1,0]] 
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.2.5
Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1


In [15]:
print(0 * np.nan) 
print(np.nan == np.nan) 
print(np.inf > np.nan) 
print(np.nan - np.nan) 
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


1.2.6 Отсортировать массив

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


1 3 1
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [28]:
arr = np.zeros((8,8), int ) #создаем массив из нулей
arr [1::2,::2] = 1 #заполняем  четные строки
arr [::2,1::2] = 1 #заполняем нечетные строки и нулевую
print(arr)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1 3 2 
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [29]:
arr = np.zeros((5,5),int)
arr += np.arange(0,5)
print (arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3
Создать массив 3x3x3 со случайными значениями.

In [19]:
np.random.randint (0, 100, (3, 3,3))

array([[[23,  0, 85],
        [ 0, 99, 71],
        [37, 47, 24]],

       [[10, 89, 69],
        [54, 95, 87],
        [47, 89, 37]],

       [[79, 94, 90],
        [56, 93, 32],
        [24, 94, 61]]])

1.3.4 Создать матрицу с 0 внутри, и 1 на границах.

In [32]:
arr = np.ones((5,5),int)
arr[1:-1,1:-1] = 0 #заполняем центр нулями
print (arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


1.3.5 Создайте массив и отсортируйте его по убыванию.

In [25]:
np.sort(np.random.randint(0,100,10))

array([ 3,  4,  5, 12, 40, 63, 83, 83, 88, 95])

1.3.6 Создайте матрицу, выведите ее форму, размер и размерность.

In [36]:
import numpy as np 
y = np.random.randint(0,100,(3,3))
print (y.shape) #Вывод размера

(3, 3)


2.2.1
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего). 

In [35]:
import pandas as pd
lst = [1, 2, 3, 4, 5] 
d = {'a':1, 'b':2, 'c':3} 
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst) 
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])
print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


2.2.2
Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [37]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e']) 
s2 = pd.Series([5, 4, 3, 2, 1]) 
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


2.2.3 Создайте новый фрейм данных.

In [38]:
dataframe = pd. DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон'] 
dataframe['Возраст'] = [38, 25] 
dataframe['Водитель'] = [True, False] 
dataframe


Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

2.2.4 Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titan
ic.csv


In [41]:
# Создать URL-адрес
url = ("https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv") # Загрузить данные 
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe. head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

2.2.5 Пронализировать характеристики фрейма данных.


In [42]:
dataframe.head(2) 
dataframe.tail(3)
dataframe.shape 
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

2.2.6 Выберите индивидуальные данные или срезы фрейма данных.

In [43]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

2.2.7 Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.


2.3.1 Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [1]:
import pandas as pd
import numpy as np

a = pd.Series(np.random.randint(0,10,(5)))
b = pd.Series(np.random.randint(0,10,(5)))

c = sum((a - b)**2)**0.5
print (c)

6.082762530298219


2.3.2 
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [6]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/akmand/datasets/main/bank_marketing.csv"
dataframe = pd.read_csv(url) 
dataframe.head(45211)


V1            V2        V3         V4  V5    V6   V7   V8         V9  \
0      58    management   married   tertiary  no  2143  yes   no    unknown   
1      44    technician    single  secondary  no    29  yes   no    unknown   
2      33  entrepreneur   married  secondary  no     2  yes  yes    unknown   
3      47   blue-collar   married    unknown  no  1506  yes   no    unknown   
4      33       unknown    single    unknown  no     1   no   no    unknown   
...    ..           ...       ...        ...  ..   ...  ...  ...        ...   
45206  51    technician   married   tertiary  no   825   no   no   cellular   
45207  71       retired  divorced    primary  no  1729   no   no   cellular   
45208  72       retired   married  secondary  no  5715   no   no   cellular   
45209  57   blue-collar   married  secondary  no   668   no   no  telephone   
45210  37  entrepreneur   married  secondary  no  2971   no   no   cellular   

       V10  V11   V12  V13  V14  V15      V16  Class  
0        5  may   261    1   -1    0  unknown      1  
1        5  may   151    1   -1    0  unknown      1  
2        5  may    76    1   -1    0  unknown      1  
3        5  may    92    1   -1    0  unknown      1  
4        5  may   198    1   -1    0  unknown      1  
...    ...  ...   ...  ...  ...  ...      ...    ...  
45206   17  nov   977    3   -1    0  unknown      2  
45207   17  nov   456    2   -1    0  unknown      2  
45208   17  nov  1127    5  184    3  success      2  
45209   17  nov   508    4   -1    0  unknown      1  
45210   17  nov   361    2  188   11    other      1  

[45211 rows x 17 columns]

2.3.3
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [57]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/akmand/datasets/main/bank_marketing.csv"
dataframe = pd.read_csv(url) 
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['V4'] == 'tertiary'].head(10)

V1             V2        V3        V4   V5     V6   V7   V8       V9  V10  \
0   58     management   married  tertiary   no   2143  yes   no  unknown    5   
5   35     management   married  tertiary   no    231  yes   no  unknown    5   
6   28     management    single  tertiary   no    447  yes  yes  unknown    5   
7   42   entrepreneur  divorced  tertiary  yes      2  yes   no  unknown    5   
21  56     management   married  tertiary   no    779  yes   no  unknown    5   
26  39     management    single  tertiary   no    255  yes   no  unknown    5   
31  49     management   married  tertiary   no    378  yes   no  unknown    5   
34  51     management   married  tertiary   no  10635  yes   no  unknown    5   
46  58  self-employed   married  tertiary   no   -364  yes   no  unknown    5   
49  29     management    single  tertiary   no      0  yes   no  unknown    5   

    V11  V12  V13  V14  V15      V16  Class  
0   may  261    1   -1    0  unknown      1  
5   may  139    1   -1    0  unknown      1  
6   may  217    1   -1    0  unknown      1  
7   may  380    1   -1    0  unknown      1  
21  may  164    1   -1    0  unknown      1  
26  may  296    1   -1    0  unknown      1  
31  may  230    1   -1    0  unknown      1  
34  may  336    1   -1    0  unknown      1  
46  may  355    1   -1    0  unknown      1  
49  may  363    1   -1    0  unknown      1

3.2.1 Прошкалируйте числовой признак в диапазон между двумя значениями.

In [48]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing
# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]]) # Создать шкалировщик 
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)
#Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

3.2.2 Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [53]:
from sklearn import preprocessing
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]]) # Создать шкалировщик 
#создали скалер
scaler = preprocessing.StandardScaler()
# Преобразовать признак 
standardized = scaler.fit_transform(x)
# Показать признак
standardized
#Мы можем увидеть эффект стандартизации, обратившись к среднем значению и стандартному отклонению результата нашего решения:
print("Среднее: ", round(standardized.mean())) 
print("Стандартное отклонение: ", standardized.std())

Среднее:  0
Стандартное отклонение:  1.0


3.2.3. Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.



In [56]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21], 'B': 
                       [103.02,107.26,110.35,114.23,114.68], 
                       'c':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']]) 
dfTest

A         B      c
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

3.3.2
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [58]:
import pandas as pd
import numpy as np
from sklearn import preprocessing as p

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url) 

length = np.array(dataframe["sepal_length_cm"])
normalizedData = p.MinMaxScaler().fit_transform(length.reshape(-1,1))
print(normalizedData) #нормализация минимаксная

width = np.array(dataframe["sepal_width_cm"])
scaled_data = p.StandardScaler().fit_transform(width.reshape(-1,1))
print(scaled_data) # нормализация z-scaling 




[[0.22222222]
 [0.16666667]
 [0.11111111]
 [0.08333333]
 [0.19444444]
 [0.30555556]
 [0.08333333]
 [0.19444444]
 [0.02777778]
 [0.16666667]
 [0.30555556]
 [0.13888889]
 [0.13888889]
 [0.        ]
 [0.41666667]
 [0.38888889]
 [0.30555556]
 [0.22222222]
 [0.38888889]
 [0.22222222]
 [0.30555556]
 [0.22222222]
 [0.08333333]
 [0.22222222]
 [0.13888889]
 [0.19444444]
 [0.19444444]
 [0.25      ]
 [0.25      ]
 [0.11111111]
 [0.13888889]
 [0.30555556]
 [0.25      ]
 [0.33333333]
 [0.16666667]
 [0.19444444]
 [0.33333333]
 [0.16666667]
 [0.02777778]
 [0.22222222]
 [0.19444444]
 [0.05555556]
 [0.02777778]
 [0.19444444]
 [0.22222222]
 [0.13888889]
 [0.22222222]
 [0.08333333]
 [0.27777778]
 [0.19444444]
 [0.75      ]
 [0.58333333]
 [0.72222222]
 [0.33333333]
 [0.61111111]
 [0.38888889]
 [0.55555556]
 [0.16666667]
 [0.63888889]
 [0.25      ]
 [0.19444444]
 [0.44444444]
 [0.47222222]
 [0.5       ]
 [0.36111111]
 [0.66666667]
 [0.36111111]
 [0.41666667]
 [0.52777778]
 [0.36111111]
 [0.44444444]
 [0.5 