1 3 1
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.


In [2]:
import numpy as np

arr = np.zeros((8,8), int )
arr [1::2,::2] = 1
arr [::2,1::2] = 1
print(arr)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1 3 2 
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [3]:
import numpy as np

arr = np.zeros((5,5),int)
arr += np.arange(0,5)
print (arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3
Создать массив 3x3x3 со случайными значениями.

In [59]:
import numpy as np

np.random.randint (0, 100, (3, 3,3))

array([[[62, 62, 60],
        [70, 22, 82],
        [27, 61, 52]],

       [[79, 81, 92],
        [41, 75, 71],
        [22, 37,  1]],

       [[67, 21, 41],
        [43, 22, 23],
        [39, 24, 67]]])

1.3.4 Создать матрицу с 0 внутри, и 1 на границах.

In [58]:
import numpy as np

arr = np.ones((5,5),int)
arr[1:-1,1:-1] = 0
print (arr)





[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


1.3.5 Создайте массив и отсортируйте его по убыванию.

In [57]:
import numpy as np 

np.sort(np.random.randint(0,100,10))

array([16, 18, 42, 63, 78, 79, 83, 85, 90, 97])

1.3.6 Создайте матрицу, выведите ее форму, размер и размерность.

In [55]:
import numpy as np 
y = np.random.randint(0,100,(3,3))
print (y.shape) #size




(3, 3)


2.3.1 Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [1]:
import pandas as pd
import numpy as np

a = pd.Series(np.random.randint(0,10,(5)))
b = pd.Series(np.random.randint(0,10,(5)))

c = sum((a - b)**2)**0.5
print (c)

6.082762530298219


2.3.2 
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [6]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/akmand/datasets/main/bank_marketing.csv"
dataframe = pd.read_csv(url) 
dataframe.head(45211)


V1            V2        V3         V4  V5    V6   V7   V8         V9  \
0      58    management   married   tertiary  no  2143  yes   no    unknown   
1      44    technician    single  secondary  no    29  yes   no    unknown   
2      33  entrepreneur   married  secondary  no     2  yes  yes    unknown   
3      47   blue-collar   married    unknown  no  1506  yes   no    unknown   
4      33       unknown    single    unknown  no     1   no   no    unknown   
...    ..           ...       ...        ...  ..   ...  ...  ...        ...   
45206  51    technician   married   tertiary  no   825   no   no   cellular   
45207  71       retired  divorced    primary  no  1729   no   no   cellular   
45208  72       retired   married  secondary  no  5715   no   no   cellular   
45209  57   blue-collar   married  secondary  no   668   no   no  telephone   
45210  37  entrepreneur   married  secondary  no  2971   no   no   cellular   

       V10  V11   V12  V13  V14  V15      V16  Class  
0        5  may   261    1   -1    0  unknown      1  
1        5  may   151    1   -1    0  unknown      1  
2        5  may    76    1   -1    0  unknown      1  
3        5  may    92    1   -1    0  unknown      1  
4        5  may   198    1   -1    0  unknown      1  
...    ...  ...   ...  ...  ...  ...      ...    ...  
45206   17  nov   977    3   -1    0  unknown      2  
45207   17  nov   456    2   -1    0  unknown      2  
45208   17  nov  1127    5  184    3  success      2  
45209   17  nov   508    4   -1    0  unknown      1  
45210   17  nov   361    2  188   11    other      1  

[45211 rows x 17 columns]

2.3.3
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [15]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/akmand/datasets/main/bank_marketing.csv"
dataframe = pd.read_csv(url) 
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['V4'] == 'tertiary'].head(10)

V1             V2        V3        V4   V5     V6   V7   V8       V9  V10  \
0   58     management   married  tertiary   no   2143  yes   no  unknown    5   
5   35     management   married  tertiary   no    231  yes   no  unknown    5   
6   28     management    single  tertiary   no    447  yes  yes  unknown    5   
7   42   entrepreneur  divorced  tertiary  yes      2  yes   no  unknown    5   
21  56     management   married  tertiary   no    779  yes   no  unknown    5   
26  39     management    single  tertiary   no    255  yes   no  unknown    5   
31  49     management   married  tertiary   no    378  yes   no  unknown    5   
34  51     management   married  tertiary   no  10635  yes   no  unknown    5   
46  58  self-employed   married  tertiary   no   -364  yes   no  unknown    5   
49  29     management    single  tertiary   no      0  yes   no  unknown    5   

    V11  V12  V13  V14  V15      V16  Class  
0   may  261    1   -1    0  unknown      1  
5   may  139    1   -1    0  unknown      1  
6   may  217    1   -1    0  unknown      1  
7   may  380    1   -1    0  unknown      1  
21  may  164    1   -1    0  unknown      1  
26  may  296    1   -1    0  unknown      1  
31  may  230    1   -1    0  unknown      1  
34  may  336    1   -1    0  unknown      1  
46  may  355    1   -1    0  unknown      1  
49  may  363    1   -1    0  unknown      1

3.3.2
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [44]:
import pandas as pd
import numpy as np
from sklearn import preprocessing as p

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url) 

length = np.array(dataframe["sepal_length_cm"])
normalizedData = p.MinMaxScaler().fit_transform(length.reshape(-1,1))
print(normalizedData) #нормализация минимаксная

width = np.array(dataframe["sepal_width_cm"])
scaled_data = p.StandardScaler().fit_transform(width.reshape(-1,1))
print(scaled_data) # нормализация z-scaling 




[[0.22222222]
 [0.16666667]
 [0.11111111]
 [0.08333333]
 [0.19444444]
 [0.30555556]
 [0.08333333]
 [0.19444444]
 [0.02777778]
 [0.16666667]
 [0.30555556]
 [0.13888889]
 [0.13888889]
 [0.        ]
 [0.41666667]
 [0.38888889]
 [0.30555556]
 [0.22222222]
 [0.38888889]
 [0.22222222]
 [0.30555556]
 [0.22222222]
 [0.08333333]
 [0.22222222]
 [0.13888889]
 [0.19444444]
 [0.19444444]
 [0.25      ]
 [0.25      ]
 [0.11111111]
 [0.13888889]
 [0.30555556]
 [0.25      ]
 [0.33333333]
 [0.16666667]
 [0.19444444]
 [0.33333333]
 [0.16666667]
 [0.02777778]
 [0.22222222]
 [0.19444444]
 [0.05555556]
 [0.02777778]
 [0.19444444]
 [0.22222222]
 [0.13888889]
 [0.22222222]
 [0.08333333]
 [0.27777778]
 [0.19444444]
 [0.75      ]
 [0.58333333]
 [0.72222222]
 [0.33333333]
 [0.61111111]
 [0.38888889]
 [0.55555556]
 [0.16666667]
 [0.63888889]
 [0.25      ]
 [0.19444444]
 [0.44444444]
 [0.47222222]
 [0.5       ]
 [0.36111111]
 [0.66666667]
 [0.36111111]
 [0.41666667]
 [0.52777778]
 [0.36111111]
 [0.44444444]
 [0.5 